#!/usr/bin/env bun
// Creates (or repairs) a wiki folder. Safe to run twice: it never overwrites.
// Usage: bun setup.ts <wiki-folder> --name "My Wiki" [--brand <brand-skill-name>]
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { MANIFEST_REL, have, run } from "./common";

function arg(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i > -1 ? process.argv[i + 1] : undefined;
}

const target = process.argv[2];
if (!target || target.startsWith("--")) {
  console.error('Usage: bun setup.ts <wiki-folder> --name "My Wiki" [--brand <brand-skill-name>] [--slide-template <template-name>]');
  process.exit(1);
}

const root = resolve(target);
const name = arg("--name") ?? root.split("/").pop() ?? "wiki";
const brand = arg("--brand") ?? "none";
const slideTemplate = arg("--slide-template") ?? (brand.includes("suse") ? "suse-sovereign" : "neutral");
const skillRoot = resolve(import.meta.dir, "..");
const today = new Date().toISOString().slice(0, 10);
const made: string[] = [];

function ensureDir(rel: string) {
  const p = join(root, rel);
  if (!existsSync(p)) {
    mkdirSync(p, { recursive: true });
    made.push(rel + "/");
  }
}

function ensureFile(rel: string, content: string) {
  const p = join(root, rel);
  if (!existsSync(p)) {
    writeFileSync(p, content);
    made.push(rel);
  }
}

// 1. Folders
for (const d of [
  "raw",
  "derived",
  "wiki/sources",
  "wiki/topics",
  "wiki/entities",
  "wiki/syntheses",
  "profile",
  "outputs",
  "scripts",
]) {
  ensureDir(d);
}

// 2. Manifest
ensureFile(
  MANIFEST_REL,
  JSON.stringify({ version: 1, updatedAt: new Date().toISOString(), files: {} }, null, 2) + "\n",
);

// 3. Seed the log (append-only JSONL; index.json/map.json are generated by links.ts below)
ensureFile(
  "wiki/log.jsonl",
  JSON.stringify({ at: new Date().toISOString(), op: "setup", title: "Wiki created" }) + "\n",
);

// 4. CLAUDE.md schema from template
const templatePath = join(skillRoot, "templates", "wiki-claude.md");
if (existsSync(templatePath)) {
  const t = readFileSync(templatePath, "utf8")
    .replaceAll("{{WIKI_NAME}}", name)
    .replaceAll("{{DATE}}", today)
    .replaceAll("{{BRAND_SKILL}}", brand)
    .replaceAll("{{SLIDE_TEMPLATE}}", slideTemplate);
  ensureFile("CLAUDE.md", t);
} else if (!existsSync(join(root, "CLAUDE.md"))) {
  console.warn("warning: template wiki-claude.md not found next to this script; CLAUDE.md not created.");
}

// 5. Copy scripts into the wiki so it is self-contained.
// These are skill-owned, not user content, so they are refreshed rather than skipped:
// re-running setup on an older wiki is how it picks up new and fixed scripts.
for (const f of [
  "common.ts",
  "image.ts",
  "doctor.ts",
  "setup.ts",
  "ingest.ts",
  "manifest.ts",
  "outline.ts",
  "media.ts",
  "links.ts",
  "wiki.ts",
  "clean.ts",
  "compose-pptx.ts",
  "compose-doc.ts",
  "compose-docx.ts",
  "package.json",
  "tsconfig.json",
]) {
  const src = join(skillRoot, "scripts", f);
  const dst = join(root, "scripts", f);
  if (!existsSync(src)) continue;
  const fresh = !existsSync(dst);
  if (fresh || readFileSync(src, "utf8") !== readFileSync(dst, "utf8")) {
    cpSync(src, dst);
    made.push("scripts/" + f + (fresh ? "" : " (updated)"));
  }
}
// 5b. Copy slide/doc templates and shared brand assets (skill-owned, refreshed
// like the scripts). Users add their own templates as sibling folders under
// templates/slides/ and templates/docs/.
for (const kind of ["slides", "docs", "shared"]) {
  const srcTpl = join(skillRoot, "templates", kind);
  if (!existsSync(srcTpl)) continue;
  const dstTpl = join(root, "templates", kind);
  const fresh = !existsSync(dstTpl);
  cpSync(srcTpl, dstTpl, { recursive: true });
  made.push(`templates/${kind}/` + (fresh ? "" : " (refreshed)"));
}
ensureFile(".gitignore", "scripts/node_modules/\n.DS_Store\n");

// 6. Install script dependencies
if (existsSync(join(root, "scripts", "package.json"))) {
  const r = run(["bun", "install"], join(root, "scripts"));
  if (!r.ok) console.warn("warning: bun install failed:\n" + r.stderr);
}

// 6b. Generate wiki/index.json and wiki/map.json so queries work from minute one.
{
  const r = run(["bun", "links.ts", "--quiet"], join(root, "scripts"));
  if (!r.ok && r.stderr) console.warn("warning: links.ts failed:\n" + r.stderr);
}

// 7. Git
if (have("git")) {
  if (!existsSync(join(root, ".git"))) {
    run(["git", "init"], root);
    made.push(".git/");
  }
  run(["git", "add", "-A"], root);
  run(["git", "commit", "-m", "wiki: setup"], root);
} else {
  console.warn("warning: git not found; the wiki will have no version history.");
}

console.log(`Wiki "${name}" is ready at ${root}`);
console.log(made.length ? "Created:\n  " + made.join("\n  ") : "Nothing to create; everything was already there.");
console.log("\nNext steps:\n  1. Put source files into raw/ (subfolders are fine).\n  2. Run: bun scripts/ingest.ts\n  3. Add voice.md and quality-and-style.md to profile/ (the skill can interview you).");
