#!/usr/bin/env bun
// Creates (or repairs) a wiki folder. Safe to run twice: it never overwrites.
// Usage: bun setup.ts <wiki-folder> --name "My Wiki" [--brand <brand-skill-name>]
import { cpSync, existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { MANIFEST_REL, have, run } from "./common";

function arg(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i > -1 ? process.argv[i + 1] : undefined;
}

const target = process.argv[2];
if (!target || target.startsWith("--")) {
  console.error('Usage: bun setup.ts <wiki-folder> --name "My Wiki" [--brand <brand-skill-name>] [--slide-template <template-name>] [--bundle-skills lolly,suse-brand] [--voice-profile <name>]');
  process.exit(1);
}

const root = resolve(target);
const name = arg("--name") ?? root.split("/").pop() ?? "wiki";
const brand = arg("--brand") ?? "none";
const voiceProfile = arg("--voice-profile") ?? "none";
const slideTemplate = arg("--slide-template") ?? (brand.includes("suse") ? "suse-sovereign" : "neutral");
const skillRoot = resolve(import.meta.dir, "..");
// Sibling skills live beside this one, wherever the wiki skill itself is installed.
const skillsRoot = resolve(skillRoot, "..");
const bundleSkills = (arg("--bundle-skills") ?? "")
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);
const today = new Date().toISOString().slice(0, 10);
const made: string[] = [];

function ensureDir(rel: string) {
  const p = join(root, rel);
  if (!existsSync(p)) {
    mkdirSync(p, { recursive: true });
    made.push(rel + "/");
  }
}

function ensureFile(rel: string, content: string) {
  const p = join(root, rel);
  if (!existsSync(p)) {
    writeFileSync(p, content);
    made.push(rel);
  }
}

// 1. Folders
for (const d of [
  "raw",
  "derived",
  "wiki/sources",
  "wiki/topics",
  "wiki/entities",
  "wiki/syntheses",
  "profiles",
  "outputs",
  "scripts",
]) {
  ensureDir(d);
}

// 2. Manifest
ensureFile(
  MANIFEST_REL,
  JSON.stringify({ version: 1, updatedAt: new Date().toISOString(), files: {} }, null, 2) + "\n",
);

// 3. Seed the log (append-only JSONL; index.json/map.json are generated by links.ts below)
ensureFile(
  "wiki/log.jsonl",
  JSON.stringify({ at: new Date().toISOString(), op: "setup", title: "Wiki created" }) + "\n",
);

// 4. CLAUDE.md schema from template
const templatePath = join(skillRoot, "templates", "wiki-claude.md");
if (existsSync(templatePath)) {
  const t = readFileSync(templatePath, "utf8")
    .replaceAll("{{WIKI_NAME}}", name)
    .replaceAll("{{DATE}}", today)
    .replaceAll("{{BRAND_SKILL}}", brand)
    .replaceAll("{{SLIDE_TEMPLATE}}", slideTemplate)
    .replaceAll("{{VOICE_PROFILE}}", voiceProfile);
  ensureFile("CLAUDE.md", t);
} else if (!existsSync(join(root, "CLAUDE.md"))) {
  console.warn("warning: template wiki-claude.md not found next to this script; CLAUDE.md not created.");
}

// 5. Copy scripts into the wiki so it is self-contained.
// These are skill-owned, not user content, so they are refreshed rather than skipped:
// re-running setup on an older wiki is how it picks up new and fixed scripts.
for (const f of [
  "common.ts",
  "image.ts",
  "image.test.ts",
  "doctor.ts",
  "setup.ts",
  "setup.test.ts",
  "ingest.ts",
  "manifest.ts",
  "outline.ts",
  "outline.test.ts",
  "textpage.test.ts",
  "media.ts",
  "links.ts",
  "wiki.ts",
  "clean.ts",
  "compose-pptx.ts",
  "verify-pptx.ts",
  "verify-pptx.test.ts",
  "preview.ts",
  "preview.test.ts",
  "voice-lint.ts",
  "voice-lint.test.ts",
  "compose-doc.ts",
  "compose-docx.ts",
  "package.json",
  "tsconfig.json",
]) {
  const src = join(skillRoot, "scripts", f);
  const dst = join(root, "scripts", f);
  if (!existsSync(src)) continue;
  const fresh = !existsSync(dst);
  if (fresh || readFileSync(src, "utf8") !== readFileSync(dst, "utf8")) {
    cpSync(src, dst);
    made.push("scripts/" + f + (fresh ? "" : " (updated)"));
  }
}
// 5b. Copy slide/doc templates and shared brand assets (skill-owned, refreshed
// like the scripts). Users add their own templates as sibling folders under
// templates/slides/ and templates/docs/.
for (const kind of ["slides", "docs", "shared"]) {
  const srcTpl = join(skillRoot, "templates", kind);
  if (!existsSync(srcTpl)) continue;
  const dstTpl = join(root, "templates", kind);
  const fresh = !existsSync(dstTpl);
  cpSync(srcTpl, dstTpl, { recursive: true });
  made.push(`templates/${kind}/` + (fresh ? "" : " (refreshed)"));
}
/**
 * Copy a skill into the wiki as a REAL directory.
 *
 * The source is resolved with realpathSync first, because a skill is very often
 * installed as a symlink to a sibling repo. cpSync would otherwise copy the link
 * itself, leaving the wiki pointing at a path outside itself: it works on the
 * machine that set it up and breaks the moment the wiki is moved or the sibling
 * repo is renamed. Only the top level is dereferenced, so symlinks *inside* a
 * skill keep whatever meaning the skill gave them.
 */
function bundleSkill(src: string, dst: string): void {
  // A dst left as a symlink by an older buggy run must be removed, not copied
  // into: cpSync would follow it and write through into the linked skill repo.
  if (existsSync(dst) && lstatSync(dst).isSymbolicLink()) rmSync(dst, { force: true });
  cpSync(realpathSync(src), dst, {
    recursive: true,
    // Caches and installed dependencies are machine-local and can be large;
    // the skill regenerates both on first use.
    filter: (from) => !/(^|\/)(node_modules|\.cache|\.git)(\/|$)/.test(from),
  });
}

// 5c. Bundle the skills this wiki depends on into .claude/skills/, so a Claude
// Code session started INSIDE the wiki folder finds them. Without this the wiki
// references a visuals or brand skill it cannot load, and composing fails with
// "the lolly skill could not be found" - the wiki is only self-contained if its
// skills travel with it. Skill-owned, so refreshed like the scripts.
for (const s of bundleSkills) {
  const src = join(skillsRoot, s);
  if (!existsSync(src)) {
    console.warn(`warning: skill "${s}" not found at ${src}; not bundled.`);
    continue;
  }
  const dst = join(root, ".claude", "skills", s);
  const fresh = !existsSync(dst);
  bundleSkill(src, dst);
  made.push(`.claude/skills/${s}/` + (fresh ? "" : " (refreshed)"));
}

// 5d. The two voice skills are not optional, so every wiki gets both:
//   idiolect - owns the voice profiles under profiles/
//   hogwash  - scans and rewrites prose against those profiles
// Both ship from the same repo, so the official install is the skills CLI
// against ravan/hogwash. A locally installed copy wins when one exists, which
// is what keeps a development machine (where these skills are being edited)
// from being overwritten by a published version; re-running setup is then how
// the wiki picks up the newer local build.
const VOICE_SKILLS: Array<{ name: string; why: string }> = [
  { name: "idiolect", why: "voice profiles" },
  { name: "hogwash", why: "prose scanning and rewriting" },
];

for (const { name: skill, why } of VOICE_SKILLS) {
  const dst = join(root, ".claude", "skills", skill);
  const candidates = [
    join(skillsRoot, skill),
    join(process.env.HOME ?? "", ".claude", "skills", skill),
  ];
  const src = candidates.find((c) => existsSync(join(c, "SKILL.md")));
  if (src) {
    const fresh = !existsSync(dst);
    bundleSkill(src, dst);
    made.push(`.claude/skills/${skill}/` + (fresh ? "" : " (refreshed)"));
  } else if (!existsSync(join(dst, "SKILL.md"))) {
    console.log(`Installing the ${skill} skill (${why}) from ravan/hogwash...`);
    run(["npx", "-y", "skills", "add", "ravan/hogwash", "--skill", skill], root);
    if (existsSync(join(dst, "SKILL.md"))) {
      made.push(`.claude/skills/${skill}/`);
    } else {
      console.warn(
        `warning: could not install the ${skill} skill (${why}).\n` +
          `  Install it later from the wiki folder with: npx skills add ravan/hogwash --skill ${skill}`,
      );
    }
  }
}

// The ignore list grows as the wiki gains parts, so append what is missing
// rather than skipping an existing file: an older wiki would otherwise commit a
// bundled skill's node_modules the first time it bundles one.
{
  const rel = ".gitignore";
  const p = join(root, rel);
  const wanted = [
    "scripts/node_modules/",
    ".claude/skills/*/node_modules/",
    ".claude/skills/*/.cache/",
    ".DS_Store",
  ];
  const existing = existsSync(p) ? readFileSync(p, "utf8") : "";
  const lines = new Set(existing.split("\n").map((l) => l.trim()));
  const missing = wanted.filter((w) => !lines.has(w));
  if (missing.length) {
    const sep = existing && !existing.endsWith("\n") ? "\n" : "";
    writeFileSync(p, existing + sep + missing.join("\n") + "\n");
    made.push(rel + (existing ? " (updated)" : ""));
  }
}

// 6. Install script dependencies
if (existsSync(join(root, "scripts", "package.json"))) {
  const r = run(["bun", "install"], join(root, "scripts"));
  if (!r.ok) console.warn("warning: bun install failed:\n" + r.stderr);
}

// 6b. Generate wiki/index.json and wiki/map.json so queries work from minute one.
{
  const r = run(["bun", "links.ts", "--quiet"], join(root, "scripts"));
  if (!r.ok && r.stderr) console.warn("warning: links.ts failed:\n" + r.stderr);
}

// 7. Git
if (have("git")) {
  if (!existsSync(join(root, ".git"))) {
    run(["git", "init"], root);
    made.push(".git/");
  }
  run(["git", "add", "-A"], root);
  run(["git", "commit", "-m", "wiki: setup"], root);
} else {
  console.warn("warning: git not found; the wiki will have no version history.");
}

console.log(`Wiki "${name}" is ready at ${root}`);
console.log(made.length ? "Created:\n  " + made.join("\n  ") : "Nothing to create; everything was already there.");
console.log("\nNext steps:\n  1. Put source files into raw/ (subfolders are fine).\n  2. Run: bun scripts/ingest.ts\n  3. Say \"capture my voice\" - the bundled idiolect skill builds a voice profile in profiles/.");
