#!/usr/bin/env bun
// Query interface over the wiki's machine-readable metadata, so an agent gets
// the slice it needs instead of reading whole files. Data comes from
// wiki/index.json and wiki/map.json (regenerated by links.ts) and wiki/log.jsonl.
//
// Usage:
//   bun wiki.ts find <term...>        # search title/summary/path in the catalog
//   bun wiki.ts find --text <term...> # full-text search across page bodies
//   bun wiki.ts page <path|slug>      # one page: summary + linked/linking pages
//   bun wiki.ts hubs                  # most connected pages
//   bun wiki.ts clusters [name]       # cluster overview, or one cluster's members
//   bun wiki.ts orphans               # pages nothing links to
//   bun wiki.ts recent [n]            # last n log entries (default 10)
//   bun wiki.ts log <op> <title> [--note "..."] [--pages a.md,b.md]   # append a log entry
//   bun wiki.ts render                # write human-readable index/map/log to outputs/
import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { wikiRootOrDie } from "./common";

const root = wikiRootOrDie();
const wikiDir = join(root, "wiki");
const logPath = join(wikiDir, "log.jsonl");
const [cmd, ...rest] = process.argv.slice(2);

interface IndexPage {
  path: string;
  category: string;
  title: string;
  summary: string;
  links: number;
}
interface MapData {
  nodes: Array<{ path: string; title: string; degree: number }>;
  edges: Array<[number, number]>;
  clusters: Array<{ name: string; members: number[] }>;
  hubs: number[];
  orphans: number[];
}
interface LogEntry {
  at: string;
  op: string;
  title: string;
  note?: string;
  pages?: string[];
}

function loadJson<T>(name: string): T {
  const p = join(wikiDir, name);
  if (!existsSync(p)) {
    console.error(`wiki/${name} is missing. Run: bun scripts/links.ts`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(p, "utf8")) as T;
}
const idx = () => loadJson<{ generatedAt: string; pages: IndexPage[] }>("index.json");
const map = () => loadJson<MapData>("map.json");
const logEntries = (): LogEntry[] =>
  existsSync(logPath)
    ? readFileSync(logPath, "utf8")
        .split("\n")
        .filter(Boolean)
        .map((l) => JSON.parse(l) as LogEntry)
    : [];

const line = (p: IndexPage) => `${p.path}  [${p.category}, ${p.links} link(s)]\n    ${p.title} - ${p.summary}`;

function usageDie(): never {
  console.error(
    "Usage: bun wiki.ts find|page|hubs|clusters|orphans|recent|log|render (see the header of this file)",
  );
  process.exit(1);
}

switch (cmd) {
  case "find": {
    const textMode = rest.includes("--text");
    const terms = rest.filter((t) => t !== "--text").map((t) => t.toLowerCase());
    if (!terms.length) usageDie();
    if (!textMode) {
      const hits = idx().pages.filter((p) =>
        terms.every((t) => `${p.path} ${p.title} ${p.summary}`.toLowerCase().includes(t)),
      );
      console.log(hits.length ? hits.map(line).join("\n") : "No catalog match. Try: bun wiki.ts find --text <terms>");
      break;
    }
    // Full text: every line that contains all terms, capped so output stays small.
    const CAP = 50;
    const hits: string[] = [];
    const walk = (dir: string) => {
      for (const f of readdirSync(dir)) {
        if (f.startsWith(".")) continue;
        const p = join(dir, f);
        if (statSync(p).isDirectory()) walk(p);
        else if (f.endsWith(".md")) {
          const lines = readFileSync(p, "utf8").split("\n");
          for (let i = 0; i < lines.length && hits.length <= CAP; i++) {
            const low = lines[i]!.toLowerCase();
            if (terms.every((t) => low.includes(t)))
              hits.push(`${relative(root, p)}:${i + 1}: ${lines[i]!.trim().slice(0, 160)}`);
          }
        }
      }
    };
    walk(wikiDir);
    if (!hits.length) console.log("No match in any page body.");
    else {
      console.log(hits.slice(0, CAP).join("\n"));
      if (hits.length > CAP) console.log(`... more matches exist; narrow the terms.`);
    }
    break;
  }

  case "page": {
    const arg = rest[0];
    if (!arg) usageDie();
    const data = map();
    const pagesByPath = new Map(idx().pages.map((p) => [p.path, p]));
    const want = arg.replace(/\.md$/, "").toLowerCase();
    const i = data.nodes.findIndex(
      (n) => n.path === arg || basename(n.path, ".md").toLowerCase() === basename(want),
    );
    if (i < 0) {
      console.error(`No page matches "${arg}". Try: bun wiki.ts find ${arg}`);
      process.exit(1);
    }
    const node = data.nodes[i]!;
    const info = pagesByPath.get(node.path);
    console.log(line(info ?? ({ path: node.path, category: "?", title: node.title, summary: "", links: node.degree } as IndexPage)));
    const out = data.edges.filter(([a]) => a === i).map(([, b]) => b);
    const inn = data.edges.filter(([, b]) => b === i).map(([a]) => a);
    const describe = (j: number) => {
      const p = pagesByPath.get(data.nodes[j]!.path);
      return `  ${data.nodes[j]!.path}  - ${p?.summary ?? data.nodes[j]!.title}`;
    };
    console.log(`\nLinks to (${out.length}):`);
    for (const j of out) console.log(describe(j));
    console.log(`\nLinked from (${inn.length}):`);
    for (const j of inn) console.log(describe(j));
    const cl = data.clusters.find((c) => c.members.includes(i));
    if (cl) console.log(`\nCluster: ${cl.name} (${cl.members.length} page(s))`);
    break;
  }

  case "hubs": {
    const data = map();
    const pagesByPath = new Map(idx().pages.map((p) => [p.path, p]));
    for (const i of data.hubs) {
      const p = pagesByPath.get(data.nodes[i]!.path);
      if (p) console.log(line(p));
    }
    break;
  }

  case "clusters": {
    const data = map();
    const name = rest.join(" ").toLowerCase();
    if (!name) {
      for (const c of data.clusters) console.log(`${c.name}  (${c.members.length} page(s))`);
      console.log(`\nMembers of one: bun wiki.ts clusters <name>`);
      break;
    }
    const c = data.clusters.find((c) => c.name.toLowerCase().includes(name));
    if (!c) {
      console.error(`No cluster matches "${rest.join(" ")}".`);
      process.exit(1);
    }
    const pagesByPath = new Map(idx().pages.map((p) => [p.path, p]));
    console.log(`${c.name}  (${c.members.length} page(s)):`);
    for (const i of c.members) {
      const p = pagesByPath.get(data.nodes[i]!.path);
      if (p) console.log(line(p));
    }
    break;
  }

  case "orphans": {
    const data = map();
    if (!data.orphans.length) {
      console.log("No orphans.");
      break;
    }
    const pagesByPath = new Map(idx().pages.map((p) => [p.path, p]));
    for (const i of data.orphans) {
      const p = pagesByPath.get(data.nodes[i]!.path);
      if (p) console.log(line(p));
    }
    break;
  }

  case "recent": {
    const n = Number(rest[0] ?? 10);
    const entries = logEntries().slice(-n);
    if (!entries.length) {
      console.log("Log is empty.");
      break;
    }
    for (const e of entries)
      console.log(`${e.at.slice(0, 10)}  ${e.op}  ${e.title}${e.note ? `  - ${e.note}` : ""}`);
    break;
  }

  case "log": {
    const flags = new Map<string, string>();
    const pos: string[] = [];
    for (let i = 0; i < rest.length; i++) {
      if (rest[i] === "--note" || rest[i] === "--pages") flags.set(rest[i]!.slice(2), rest[++i] ?? "");
      else pos.push(rest[i]!);
    }
    const [op, ...titleParts] = pos;
    const title = titleParts.join(" ");
    if (!op || !title) {
      console.error('Usage: bun wiki.ts log <op> <title> [--note "..."] [--pages a.md,b.md]');
      process.exit(1);
    }
    const entry: LogEntry = { at: new Date().toISOString(), op, title };
    if (flags.get("note")) entry.note = flags.get("note");
    if (flags.get("pages")) entry.pages = flags.get("pages")!.split(",").map((s) => s.trim()).filter(Boolean);
    appendFileSync(logPath, JSON.stringify(entry) + "\n");
    console.log(`Logged: ${entry.at.slice(0, 10)} ${op} | ${title}`);
    break;
  }

  case "render": {
    // Human-readable views, written to outputs/ on demand. The JSON stays the
    // single source of truth; these are throwaway reading copies.
    const outDir = join(root, "outputs");
    mkdirSync(outDir, { recursive: true });
    const catalog = idx();
    const data = map();

    const byCat = new Map<string, IndexPage[]>();
    for (const p of catalog.pages) {
      const g = byCat.get(p.category) ?? [];
      g.push(p);
      byCat.set(p.category, g);
    }
    const relFromOutputs = (path: string) => `../${path}`;
    const indexMd: string[] = ["# Index (generated reading copy)", ""];
    for (const [cat, list] of [...byCat.entries()].sort()) {
      indexMd.push(`## ${cat}`, "");
      for (const p of list) indexMd.push(`- [${p.title}](${relFromOutputs(p.path)}) - ${p.summary}`);
      indexMd.push("");
    }
    writeFileSync(join(outDir, "index.md"), indexMd.join("\n"));

    const pagesByPath = new Map(catalog.pages.map((p) => [p.path, p]));
    const mapMd: string[] = ["# Map (generated reading copy)", "", "## Hubs", ""];
    for (const i of data.hubs) {
      const n = data.nodes[i]!;
      mapMd.push(`- [${n.title}](${relFromOutputs(n.path)}) - ${n.degree} connection(s). ${pagesByPath.get(n.path)?.summary ?? ""}`);
    }
    mapMd.push("", "## Clusters", "");
    for (const c of data.clusters) {
      mapMd.push(`### ${c.name} (${c.members.length} page(s))`, "");
      for (const i of c.members) {
        const n = data.nodes[i]!;
        mapMd.push(`- [${n.title}](${relFromOutputs(n.path)}) - ${pagesByPath.get(n.path)?.summary ?? ""}`);
      }
      mapMd.push("");
    }
    mapMd.push("## Orphans", "");
    mapMd.push(data.orphans.length ? data.orphans.map((i) => `- [${data.nodes[i]!.title}](${relFromOutputs(data.nodes[i]!.path)})`).join("\n") : "(none)", "");
    writeFileSync(join(outDir, "map.md"), mapMd.join("\n"));

    const logMd: string[] = ["# Log (generated reading copy)", ""];
    for (const e of logEntries())
      logMd.push(`## [${e.at.slice(0, 10)}] ${e.op} | ${e.title}`, "", ...(e.note ? [e.note, ""] : []));
    writeFileSync(join(outDir, "log.md"), logMd.join("\n"));

    console.log("Wrote outputs/index.md, outputs/map.md, outputs/log.md (reading copies; the JSON stays authoritative).");
    break;
  }

  default:
    usageDie();
}
